[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
lib_deps =
    https://github.com/adafruit/Adafruit_Seesaw.git
    https://github.com/adafruit/Adafruit_SHT31.git
    https://github.com/Dlloydev/QuickPID.git
    https://github.com/br3ttb/Arduino-PID-Library.git
    ; https://github.com/panStamp/thermistor.git
    ; https://github.com/suoapvs/NTC_Thermistor.git
    SPI
    Adafruit BusIO
    paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6




[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM


[env:adafruit_qtpy_esp32s2]
board = adafruit_qtpy_esp32s2


